### ISSUE TITLE
Incompatible with HTTPS Everywhere

### ISSUE THREAD

**Issue by Pichu0102** [jparise/chrome-utm-stripper#13]
When used with HTTPS everywhere, the extension throws an error:

`Warning:
This extension failed to redirect a network request to http://theweek.com/articles/687917/took-multivitamins-every-day-decade-found-theyre-useless?ICID=ref_fark because another extension (HTTPS Everywhere) redirected it to https://theweek.com/articles/687917/took-multivitamins-every-day-decade-found-theyre-useless?utm_source=fark&amp;utm_medium=website&amp;utm_content=link&amp;ICID=r`

**Comment by Kasijjuf** [comment]
Ideally, these two add-ons should work together in sequence with this add-on first stripping the URL of utm parameters and then HTTPS Everywhere redirecting the resulting URL.

**Comment by jparise** [comment]
I spent some more time trying to figure out how to work around this issue. The root of the problem (from [Chrome's webRequest documentation](https://developer.chrome.com/extensions/webRequest)):

> Only one extension is allowed to redirect a request or modify a header at a time. If more than one extension attempts to modify the request, the most recently installed extension wins and all others are ignored. An extension is not notified if its instruction to modify or redirect has been ignored.

... and because both extensions use redirects to "fix" the original URL, Chrome (helpfully?) flags the conflict.

I'm open to suggestions on how best to work around this issue. At the moment, I don't have any ideas aside from officially calling out the incompatibility.

See also EFForg/https-everywhere#6034, which identifies some other extensions that run into this conflict, too.

**Comment by mikhoul** [comment]
> I'm open to suggestions on how best to work around this issue. At the moment, I don't have any ideas aside from officially calling

I'm new to Chrome (from Firefox) and I was browsing Github to look at the extension available and found this thread...

I have a suggestion that could work if you do a Userscript that could work with Tampermonkey


```
// ==UserScript==
// @name        UTM Stripper
// @namespace   http://userscripts.org/scripts/show/71813
// @description Strips Urchin Tracker Module (UTM) tags from visited URLs
// @why         UTM makes URLs way too long, possibly confuses URL-sharing sites
// @note        UTM Stripper does NOT prevent analytics data from being sent out. This script only runs after a page has loaded WITH the UTM tags in place. 
// @copyright   2010+, Michael Gram, http://userscripts.org/scripts/show/71813
// @license     GPLv3--http://www.gnu.org/copyleft/gpl.html
// @license     Creative Commons--http://creativecommons.org/licenses/by-nc-sa/3.0
// @version     1.0.2
 /*     http://*.tld/*utm_source*  */
// @include http://www.viralands.com/*
// ==/UserScript==

function stripUTM()
{
var utm_href = window.location.href

var utm_index = utm_href.indexOf("?utm_source")

if (utm_index == -1)
    {
    utm_index = utm_href.indexOf("&utm_source")
    }

var new_href = utm_href.substr(0, utm_index)

window.location.href = new_href
}

window.setTimeout(stripUTM,0)
```

Since the script is Open source you could change it to fit your own needs.


Regards :octocat:

**Comment by jparise** [comment]
[HTTP Everywhere is now in maintenance mode.](https://www.eff.org/deeplinks/2021/09/https-actually-everywhere)
