### ISSUE TITLE
Just a "little-more-off-the-top", please.

### ISSUE THREAD

**Issue by kcnickerson** [jparise/chrome-utm-stripper#22]
Great plugin, works (Firefox) but still leaves the residue from the tracking, so each-and-every URL save needs to be manually fixed. Please update. Thank you.

Pre-Strip:
https://singularityhub.com/2018/10/31/can-we-program-ethics-into-self-driving-cars/?fbclid=IwAR0bMFIAgBep3uprdKETFxjVAeEgnQr0rbeZ30BntmexxPp-4wVUyQzjudQ#sm.0000f7a6zxtenfqsqyf2108zz7d9t

Post-Strip:
https://singularityhub.com/2018/10/31/can-we-program-ethics-into-self-driving-cars/#sm.0000f7a6zxtenfqsqyf2108zz7d9t

Desired-Strip:
https://singularityhub.com/2018/10/31/can-we-program-ethics-into-self-driving-cars/

**Comment by jparise** [comment]
I'm afraid the goal of this extension _isn't_ to be a generic URL cleaner. You might instead be interested in an extension like [Link Cleaner](https://addons.mozilla.org/en-US/firefox/addon/link-cleaner/), which handles more types of query string tokens and offers user configuration.

I started this particular extension before I found those others (and because my needs were simpler), and I don't see the need to "reinvent the wheel" at this point when there are other good solutions available.
